apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-micro
  name: go-micro-client
spec:
  selector:
    matchLabels:
      app: go-micro-client
  replicas: 2
  template:
    metadata:
      labels:
        app: go-micro-client
    spec:
      containers:
        - name: go-micro-client
          image: liuyao/go-micro-client:kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              name: http-port


